export const ORDER_ACTIONS ={
    ADD_ORDER_SUCCESS : "ADD_ORDER_SUCCESS",
    ADD_ORDER_ERROR : "ADD_ORDER_ERROR",
    UPDATE_ORDER: "UPDATE_ORDER"
}

export const ORDER_STATUS ={
    CREATED: "CREATED",
    IN_PROGRESS: "IN_PROGRESS",
    DONE:"DONE"
}